import { Messaging } from './messaging';
import { Order } from './order';
import { Persistency } from './persistency';
import { Product } from './product';
import { ShoppingCart } from './shopping-cart';
import { FiftyPercentDiscount, TenPercentDiscount } from './discount';
const fiftyPercentDiscount = new FiftyPercentDiscount();
const tenPercentDiscount = new TenPercentDiscount();
const shoppingCart = new ShoppingCart(tenPercentDiscount);
const messaging = new Messaging();
const persistency = new Persistency();
const order = new Order(shoppingCart, messaging, persistency);
shoppingCart.addItem(new Product('Camisa', 10));
shoppingCart.addItem(new Product('Calça', 10));
console.log(shoppingCart.items);
console.log('total:', shoppingCart.total());
console.log('totalWithDiscount:' + shoppingCart.totalWithDiscount());
order.checkout();
